PATCH /api/2.5/tenders/ae2274f0782747918bb1e96f34787c24/bids/91c7aa33638e4680980085954fdc33a8/documents/4863fce439934b57a69fcc1076186e70?acc_token=8e071dd39f464632a4bbfec1d3158ff9 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "confidentiality": "buyerOnly",
    "confidentialityRationale": "Only our company sells badgers with pink hair."
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "confidentiality": "buyerOnly",
    "confidentialityRationale": "Only our company sells badgers with pink hair.",
    "id": "4863fce439934b57a69fcc1076186e70",
    "datePublished": "2023-10-10T01:00:00+03:00",
    "hash": "md5:00000000000000000000000000000000",
    "title": "Proposal_top_secrets.pdf",
    "format": "application/pdf",
    "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/ae2274f0782747918bb1e96f34787c24/bids/91c7aa33638e4680980085954fdc33a8/documents/4863fce439934b57a69fcc1076186e70?download=c24f82881bbb413090880c729b494aae",
    "documentOf": "tender",
    "dateModified": "2023-10-10T01:00:00+03:00",
    "language": "uk"
  }
}

