POST /api/2.5/tenders/13ccc4a94b884c8c8abe24e6299e865e/plans?acc_token=2ff9a6b5f48b4428b2d9652451e3b3be HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "id": "d1b27c777c30402190752796d48859fd"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": [
    {
      "id": "d1b27c777c30402190752796d48859fd"
    }
  ]
}

