POST /api/2.5/tenders/2874d5c2acd649bbb8679e9439621113/cancellations?acc_token=3f07ab10456e4f519a3cf51c24d19c80 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "reason": "cancellation reason",
    "reasonType": "noDemand"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/2874d5c2acd649bbb8679e9439621113/cancellations/ad5fdab416c8405789f80308b835a91f

{
  "data": {
    "reasonType": "noDemand",
    "reason": "cancellation reason",
    "id": "ad5fdab416c8405789f80308b835a91f",
    "date": "2024-01-01T00:00:01+02:00",
    "cancellationOf": "tender",
    "status": "draft"
  }
}

