PATCH /api/2.5/tenders/afbae9188b434d3bb77426b13e9a5165/bids/f4f4958a25d641dc903708cc957eab58?acc_token=60f4f451f2864f7e9428372a1316e992 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "pending"
  }
}


HTTP/1.0 422 Unprocessable Entity
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "documents",
      "description": "Document with type 'proposal' and format pkcs7-signature is required"
    }
  ]
}

