DELETE /api/2.5/tenders/9ced6e51f90943439764928675f07e53/lots/00c2559f4fcb4104964eb69b22e5c112?acc_token=bf0080ab5dfc458db33c0823644645d9 HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua


HTTP/1.0 422 Unprocessable Entity
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "data",
      "description": "Cannot delete lot with related milestones"
    }
  ]
}

