POST /api/2.5/tenders/8c3e76b8d9cc43d0bdb4c17cd43538ba/bids/75914cdd9ee240558ae42ebaa6400c31/requirement_responses/3410016d837b44a4902ed3d1aebf3c50/evidences?acc_token=c62253cf3f364c0eac1ff2fff02c69a6 HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Requirement response",
    "relatedDocument": {
      "id": "4b239698bd5843089f0497720a38d97d",
      "title": "name.doc"
    },
    "type": "document"
  }
}


HTTP/1.0 201 Created
Content-Type: application/json

{
  "data": {
    "title": "Requirement response",
    "type": "document",
    "relatedDocument": {
      "id": "4b239698bd5843089f0497720a38d97d",
      "title": "name.doc"
    },
    "id": "20af3de472e742c88d1d02067b97c399"
  }
}

