DELETE /api/2.5/tenders/8c3e76b8d9cc43d0bdb4c17cd43538ba/bids/75914cdd9ee240558ae42ebaa6400c31/requirement_responses/00bc7d356cc04f339b1cda48f2d95b48?acc_token=c62253cf3f364c0eac1ff2fff02c69a6 HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "requirement": {
      "id": "a747a1ae52274ff7a874cc50410f9fa9",
      "title": "Учасник процедури закупівлі не був засуджений за кримінальне правопорушення, вчинене з корисливих мотивів (зокрема, пов’язане з хабарництвом та відмиванням коштів), судимість з якої знято або погашено у встановленому законом порядку"
    },
    "value": true,
    "id": "00bc7d356cc04f339b1cda48f2d95b48",
    "classification": {
      "scheme": "ESPD211",
      "id": "CRITERION.EXCLUSION.CONVICTIONS.PARTICIPATION_IN_CRIMINAL_ORGANISATION"
    }
  }
}

