GET /api/2.5/submissions/da4552d132e14fd19dc2d64f1438a0d1/documents/95897799b92c4866b2e932206f8cf013?download=1 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 403 Forbidden
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "data",
      "description": "Document download forbidden."
    }
  ]
}

