POST /api/2.5/tenders/e3ba356ffdb04f32b1864a591633a385/complaints/87323fb969f9439a8921fdd9bb6e1c26/posts?acc_token=e3de4cad10924527927b751b1ceeae1b HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Відповідь до пояснення",
    "description": "Відсутній документ",
    "recipient": "aboveThresholdReviewers",
    "relatedObjection": "21fd7cec213743589b967e42ed0752bd",
    "relatedPost": "a1f633c687464f6794cd9fe5d20623a3"
  }
}


HTTP/1.0 422 Unprocessable Entity
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "relatedPost",
      "description": [
        "forbidden to answer to explanations"
      ]
    }
  ]
}

