POST /api/2.5/tenders/e3ba356ffdb04f32b1864a591633a385/complaints/87323fb969f9439a8921fdd9bb6e1c26/documents?acc_token=e3de4cad10924527927b751b1ceeae1b HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "post_document_tender.pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c8fd6150be5a4619bda0992913c6c146?Signature=dYukmfu5ESlKj4Vm114HI1NIlDUt6%2F%2FnNWwITLzbXdLbTT1g%2B4mJCH5%2FWE6zjqMtuaNd4hryU9mBnC8leSLYCQ%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/pdf",
    "documentOf": "post",
    "relatedItem": "293df18ec6e440398224e82c519744b2"
  }
}


HTTP/1.0 403 Forbidden
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "url",
      "name": "role",
      "description": "Can add document to post only by post author"
    }
  ]
}

