POST /api/2.5/tenders/197ab221daff4d87b98cf8e0d03cb393/qualifications/2d78f58e5c164ddf82bfdc25666fd652/complaints/43b369b101664c48be3959cdb9926838/posts?acc_token=72ce97a3f67b4f5280d57ba22f0e597a HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "Відповідь до пояснення",
    "description": "Відсутній документ",
    "recipient": "aboveThresholdReviewers",
    "relatedObjection": "e424fd9b73c046268255bd219f528456",
    "relatedPost": "acb635ad760448b6b0cc6bfd1803b8db"
  }
}


HTTP/1.0 422 Unprocessable Entity
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "relatedPost",
      "description": [
        "forbidden to answer to explanations"
      ]
    }
  ]
}

