POST /api/2.5/tenders/197ab221daff4d87b98cf8e0d03cb393/qualifications/2d78f58e5c164ddf82bfdc25666fd652/complaints/43b369b101664c48be3959cdb9926838/documents?acc_token=72ce97a3f67b4f5280d57ba22f0e597a HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "title": "post_document_tender.pdf",
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a450311edb8e418082d4746c150e309c?Signature=ie%2FvZJ5uVGGOPp5i7ipeO75tMkkY1EkeumZK2C77mwjIjkJjPRqQKbu7EWFWHeQX3k8hrz2e3rzpLLn0qdFtBg%3D%3D&KeyID=a8968c46",
    "hash": "md5:00000000000000000000000000000000",
    "format": "application/pdf",
    "documentOf": "post",
    "relatedItem": "951bf9f29bb44912a055c98d3853c468"
  }
}


HTTP/1.0 403 Forbidden
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "url",
      "name": "role",
      "description": "Can add document to post only by post author"
    }
  ]
}

