PATCH /api/2.5/tenders/0c99535af6024017bcbdec7b4a5c49da/bids/9d1348ad3820464db3213aaf48a1f51b?acc_token=66a6b63fed61401a8d6a987739bf9a9c HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "requirementResponses": []
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

null

