POST /api/2.5/tenders/e331845136c14af1a03b59e13c030ae1/ownership HTTP/1.0
Authorization: Bearer broker1
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "id": "efa43e6ae91e40e3bf1cc9e7c08a51c5",
    "transfer": "6d25791d89994de4bb70f222c937647f"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "owner": "broker1",
    "id": "e331845136c14af1a03b59e13c030ae1"
  }
}

