POST /api/2.5/tenders/e331845136c14af1a03b59e13c030ae1/ownership HTTP/1.0
Authorization: Bearer broker2
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "id": "8d5570ccc82a4e2f82fe3d2c01729d8e",
    "transfer": "6d25791d89994de4bb70f222c937647f"
  }
}


HTTP/1.0 403 Forbidden
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "url",
      "name": "accreditation",
      "description": "Broker Accreditation level does not permit ownership change"
    }
  ]
}

