POST /api/2.5/plans/5e6819d2385c4c6a8a7877b87488074c/ownership HTTP/1.0
Authorization: Bearer broker1
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "id": "6681cf91ab4c4f1e919c18d368a16c25",
    "transfer": "9192aab96d4b4959affa7d7644f539a6"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "owner": "broker1",
    "id": "5e6819d2385c4c6a8a7877b87488074c"
  }
}

