POST /api/2.5/plans/5e6819d2385c4c6a8a7877b87488074c/ownership HTTP/1.0
Authorization: Bearer brokerx
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "id": "ea8708a2c6f046d39672eb4ddae4aefd",
    "transfer": "9192aab96d4b4959affa7d7644f539a6"
  }
}


HTTP/1.0 403 Forbidden
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "url",
      "name": "accreditation",
      "description": "Owner Accreditation level does not permit ownership change"
    }
  ]
}

