PATCH /api/2.5/tenders/7443f2bcc1da4f3ab5400ac8216c5692/cancellations/8fdaed08e00c49468fa9bf713248ee91?acc_token=955ba98fce244b3aa2cd16bcdbd01e2a HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "status": "pending"
  }
}


HTTP/1.0 422 Unprocessable Entity
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "documents",
      "description": "Document with type 'cancellationReport' and format pkcs7-signature is required"
    }
  ]
}

