GET /api/2.5/tenders/4a2a576c85d54712935397876296f0d9/bids/3088275f136046dab34594e16227bb54?opt_context=true HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 403 Forbidden
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "data",
      "description": "Can't view bid in current (active.tendering) tender status"
    }
  ]
}

