GET /api/2.5/submissions/279fcb35af574cc388bdef2edadaccec/documents/4259f769559d4b3b8259fd39d013a36f?download=1 HTTP/1.0
Authorization: Bearer broker
Host: public-api-sandbox.prozorro.gov.ua


HTTP/1.0 403 Forbidden
Content-Type: application/json

{
  "status": "error",
  "errors": [
    {
      "location": "body",
      "name": "data",
      "description": "Document download forbidden."
    }
  ]
}

