PATCH /api/2.5/frameworks/fa6d3c736b93497ba582111050651a00/questions/74139d6073c243338cc9711442f595e9?acc_token=eee7b4b7d48f46658ee6f0e88893704a HTTP/1.0
Authorization: Bearer broker
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

{
  "data": {
    "answer": "Таблицю додано в файлі"
  }
}


HTTP/1.0 200 OK
Content-Type: application/json

{
  "data": {
    "id": "74139d6073c243338cc9711442f595e9",
    "author": {
      "hash": "5cdd54ddce50afbec0552daa4496bba6"
    },
    "title": "Калорійність",
    "description": "Просимо додати таблицю потрібної калорійності харчування",
    "date": "2023-01-01T00:00:00+02:00",
    "answer": "Таблицю додано в файлі",
    "dateAnswered": "2023-01-01T00:00:00+02:00"
  }
}

